/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SkillsPassportRouteImport } from './routes/skills-passport'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResumeBuilderRouteImport } from './routes/resume-builder'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyCvRouteImport } from './routes/my-cv'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkedinReviewRouteImport } from './routes/linkedin-review'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InterviewPreparationRouteImport } from './routes/interview-preparation'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseworkerRouteImport } from './routes/caseworker'
import { Route as CareerPathwayRouteImport } from './routes/career-pathway'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PocVacancyParserRouteImport } from './routes/poc.vacancy-parser'
import { Route as PocRecommendationsRouteImport } from './routes/poc.recommendations'
import { Route as PocEmployerMatchingRouteImport } from './routes/poc.employer-matching'
import { Route as PocDashboardRouteImport } from './routes/poc.dashboard'
import { Route as PocAiMatchingRouteImport } from './routes/poc.ai-matching'
import { Route as LinkedinReviewResultsRouteImport } from './routes/linkedin-review.results'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as InterviewSetupRouteImport } from './routes/interview.setup'
import { Route as InterviewSessionIdRouteImport } from './routes/interview.$sessionId'
import { Route as EmployerVacancyBuilderRouteImport } from './routes/employer.vacancy-builder'
import { Route as EmployerTalentDiscoveryRouteImport } from './routes/employer.talent-discovery'
import { Route as EmployerSignupRouteImport } from './routes/employer.signup'
import { Route as EmployerOccupationIntelligenceRouteImport } from './routes/employer.occupation-intelligence'
import { Route as EmployerLoginRouteImport } from './routes/employer.login'
import { Route as EmployerLabourMarketIntelligenceRouteImport } from './routes/employer.labour-market-intelligence'
import { Route as EmployerInterviewsRouteImport } from './routes/employer.interviews'
import { Route as EmployerInterviewTemplatesRouteImport } from './routes/employer.interview-templates'
import { Route as EmployerDashboardRouteImport } from './routes/employer.dashboard'
import { Route as CaseworkerCandidateIdRouteImport } from './routes/caseworker.$candidateId'
import { Route as ApplicationApplicationIdRouteImport } from './routes/application.$applicationId'
import { Route as ApiResumeBuilderRouteImport } from './routes/api.resume-builder'
import { Route as ApiOpsRouteImport } from './routes/api.ops'
import { Route as ApiInterviewRouteImport } from './routes/api.interview'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTaxonomyRouteImport } from './routes/admin.taxonomy'
import { Route as AdminSystemMonitoringRouteImport } from './routes/admin.system-monitoring'
import { Route as AdminRbacRouteImport } from './routes/admin.rbac'
import { Route as AdminPlacementsRouteImport } from './routes/admin.placements'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEmployersRouteImport } from './routes/admin.employers'
import { Route as AdminConfigurationRouteImport } from './routes/admin.configuration'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as InterviewSessionIdSummaryRouteImport } from './routes/interview.$sessionId.summary'
import { Route as InterviewSessionIdRoomRouteImport } from './routes/interview.$sessionId.room'
import { Route as EmployerInterviewsCreateRouteImport } from './routes/employer.interviews.create'
import { Route as EmployerInterviewTemplatesCreateRouteImport } from './routes/employer.interview-templates.create'
import { Route as EmployerInterviewTemplatesTemplateIdRouteImport } from './routes/employer.interview-templates.$templateId'
import { Route as EmployerCandidateCandidateIdRouteImport } from './routes/employer.candidate.$candidateId'
import { Route as AdminCandidatesCandidateIdRouteImport } from './routes/admin.candidates.$candidateId'
import { Route as EmployerVacancyJobIdOptimizeRouteImport } from './routes/employer.vacancy.$jobId.optimize'
import { Route as EmployerVacanciesJobIdOccupationRouteImport } from './routes/employer.vacancies.$jobId.occupation'
import { Route as EmployerVacanciesJobIdIntelligenceRouteImport } from './routes/employer.vacancies.$jobId.intelligence'
import { Route as EmployerVacanciesJobIdCandidatesRouteImport } from './routes/employer.vacancies.$jobId.candidates'
import { Route as EmployerInterviewsSessionIdReportRouteImport } from './routes/employer.interviews.$sessionId.report'
import { Route as EmployerVacanciesJobIdCandidatesCompareRouteImport } from './routes/employer.vacancies.$jobId.candidates.compare'
import { Route as EmployerVacanciesJobIdCandidatesCandidateIdRouteImport } from './routes/employer.vacancies.$jobId.candidates.$candidateId'
import { Route as EmployerInterviewTemplatesTemplateIdReportInvitationIdRouteImport } from './routes/employer.interview-templates.$templateId.report.$invitationId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsPassportRoute = SkillsPassportRouteImport.update({
  id: '/skills-passport',
  path: '/skills-passport',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBuilderRoute = ResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCvRoute = MyCvRouteImport.update({
  id: '/my-cv',
  path: '/my-cv',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinReviewRoute = LinkedinReviewRouteImport.update({
  id: '/linkedin-review',
  path: '/linkedin-review',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewPreparationRoute = InterviewPreparationRouteImport.update({
  id: '/interview-preparation',
  path: '/interview-preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseworkerRoute = CaseworkerRouteImport.update({
  id: '/caseworker',
  path: '/caseworker',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerPathwayRoute = CareerPathwayRouteImport.update({
  id: '/career-pathway',
  path: '/career-pathway',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PocVacancyParserRoute = PocVacancyParserRouteImport.update({
  id: '/poc/vacancy-parser',
  path: '/poc/vacancy-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const PocRecommendationsRoute = PocRecommendationsRouteImport.update({
  id: '/poc/recommendations',
  path: '/poc/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const PocEmployerMatchingRoute = PocEmployerMatchingRouteImport.update({
  id: '/poc/employer-matching',
  path: '/poc/employer-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const PocDashboardRoute = PocDashboardRouteImport.update({
  id: '/poc/dashboard',
  path: '/poc/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PocAiMatchingRoute = PocAiMatchingRouteImport.update({
  id: '/poc/ai-matching',
  path: '/poc/ai-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinReviewResultsRoute = LinkedinReviewResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => LinkedinReviewRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const InterviewSetupRoute = InterviewSetupRouteImport.update({
  id: '/interview/setup',
  path: '/interview/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewSessionIdRoute = InterviewSessionIdRouteImport.update({
  id: '/interview/$sessionId',
  path: '/interview/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerVacancyBuilderRoute = EmployerVacancyBuilderRouteImport.update({
  id: '/employer/vacancy-builder',
  path: '/employer/vacancy-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerTalentDiscoveryRoute = EmployerTalentDiscoveryRouteImport.update({
  id: '/employer/talent-discovery',
  path: '/employer/talent-discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerSignupRoute = EmployerSignupRouteImport.update({
  id: '/employer/signup',
  path: '/employer/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerOccupationIntelligenceRoute =
  EmployerOccupationIntelligenceRouteImport.update({
    id: '/employer/occupation-intelligence',
    path: '/employer/occupation-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployerLoginRoute = EmployerLoginRouteImport.update({
  id: '/employer/login',
  path: '/employer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerLabourMarketIntelligenceRoute =
  EmployerLabourMarketIntelligenceRouteImport.update({
    id: '/employer/labour-market-intelligence',
    path: '/employer/labour-market-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployerInterviewsRoute = EmployerInterviewsRouteImport.update({
  id: '/employer/interviews',
  path: '/employer/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerInterviewTemplatesRoute =
  EmployerInterviewTemplatesRouteImport.update({
    id: '/employer/interview-templates',
    path: '/employer/interview-templates',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployerDashboardRoute = EmployerDashboardRouteImport.update({
  id: '/employer/dashboard',
  path: '/employer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseworkerCandidateIdRoute = CaseworkerCandidateIdRouteImport.update({
  id: '/$candidateId',
  path: '/$candidateId',
  getParentRoute: () => CaseworkerRoute,
} as any)
const ApplicationApplicationIdRoute =
  ApplicationApplicationIdRouteImport.update({
    id: '/application/$applicationId',
    path: '/application/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiResumeBuilderRoute = ApiResumeBuilderRouteImport.update({
  id: '/api/resume-builder',
  path: '/api/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsRoute = ApiOpsRouteImport.update({
  id: '/api/ops',
  path: '/api/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewRoute = ApiInterviewRouteImport.update({
  id: '/api/interview',
  path: '/api/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTaxonomyRoute = AdminTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemMonitoringRoute = AdminSystemMonitoringRouteImport.update({
  id: '/system-monitoring',
  path: '/system-monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRbacRoute = AdminRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacementsRoute = AdminPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployersRoute = AdminEmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigurationRoute = AdminConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const InterviewSessionIdSummaryRoute =
  InterviewSessionIdSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => InterviewSessionIdRoute,
  } as any)
const InterviewSessionIdRoomRoute = InterviewSessionIdRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => InterviewSessionIdRoute,
} as any)
const EmployerInterviewsCreateRoute =
  EmployerInterviewsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => EmployerInterviewsRoute,
  } as any)
const EmployerInterviewTemplatesCreateRoute =
  EmployerInterviewTemplatesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => EmployerInterviewTemplatesRoute,
  } as any)
const EmployerInterviewTemplatesTemplateIdRoute =
  EmployerInterviewTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => EmployerInterviewTemplatesRoute,
  } as any)
const EmployerCandidateCandidateIdRoute =
  EmployerCandidateCandidateIdRouteImport.update({
    id: '/employer/candidate/$candidateId',
    path: '/employer/candidate/$candidateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCandidatesCandidateIdRoute =
  AdminCandidatesCandidateIdRouteImport.update({
    id: '/$candidateId',
    path: '/$candidateId',
    getParentRoute: () => AdminCandidatesRoute,
  } as any)
const EmployerVacancyJobIdOptimizeRoute =
  EmployerVacancyJobIdOptimizeRouteImport.update({
    id: '/employer/vacancy/$jobId/optimize',
    path: '/employer/vacancy/$jobId/optimize',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployerVacanciesJobIdOccupationRoute =
  EmployerVacanciesJobIdOccupationRouteImport.update({
    id: '/employer/vacancies/$jobId/occupation',
    path: '/employer/vacancies/$jobId/occupation',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployerVacanciesJobIdIntelligenceRoute =
  EmployerVacanciesJobIdIntelligenceRouteImport.update({
    id: '/employer/vacancies/$jobId/intelligence',
    path: '/employer/vacancies/$jobId/intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployerVacanciesJobIdCandidatesRoute =
  EmployerVacanciesJobIdCandidatesRouteImport.update({
    id: '/employer/vacancies/$jobId/candidates',
    path: '/employer/vacancies/$jobId/candidates',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployerInterviewsSessionIdReportRoute =
  EmployerInterviewsSessionIdReportRouteImport.update({
    id: '/$sessionId/report',
    path: '/$sessionId/report',
    getParentRoute: () => EmployerInterviewsRoute,
  } as any)
const EmployerVacanciesJobIdCandidatesCompareRoute =
  EmployerVacanciesJobIdCandidatesCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => EmployerVacanciesJobIdCandidatesRoute,
  } as any)
const EmployerVacanciesJobIdCandidatesCandidateIdRoute =
  EmployerVacanciesJobIdCandidatesCandidateIdRouteImport.update({
    id: '/$candidateId',
    path: '/$candidateId',
    getParentRoute: () => EmployerVacanciesJobIdCandidatesRoute,
  } as any)
const EmployerInterviewTemplatesTemplateIdReportInvitationIdRoute =
  EmployerInterviewTemplatesTemplateIdReportInvitationIdRouteImport.update({
    id: '/report/$invitationId',
    path: '/report/$invitationId',
    getParentRoute: () => EmployerInterviewTemplatesTemplateIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/analyze': typeof AnalyzeRoute
  '/career-pathway': typeof CareerPathwayRoute
  '/caseworker': typeof CaseworkerRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/interview-preparation': typeof InterviewPreparationRoute
  '/jobs': typeof JobsRouteWithChildren
  '/linkedin-review': typeof LinkedinReviewRouteWithChildren
  '/login': typeof LoginRoute
  '/my-cv': typeof MyCvRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/signup': typeof SignupRoute
  '/skills-passport': typeof SkillsPassportRoute
  '/terms': typeof TermsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/candidates': typeof AdminCandidatesRouteWithChildren
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/employers': typeof AdminEmployersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/system-monitoring': typeof AdminSystemMonitoringRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/ops': typeof ApiOpsRoute
  '/api/resume-builder': typeof ApiResumeBuilderRoute
  '/application/$applicationId': typeof ApplicationApplicationIdRoute
  '/caseworker/$candidateId': typeof CaseworkerCandidateIdRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/interview-templates': typeof EmployerInterviewTemplatesRouteWithChildren
  '/employer/interviews': typeof EmployerInterviewsRouteWithChildren
  '/employer/labour-market-intelligence': typeof EmployerLabourMarketIntelligenceRoute
  '/employer/login': typeof EmployerLoginRoute
  '/employer/occupation-intelligence': typeof EmployerOccupationIntelligenceRoute
  '/employer/signup': typeof EmployerSignupRoute
  '/employer/talent-discovery': typeof EmployerTalentDiscoveryRoute
  '/employer/vacancy-builder': typeof EmployerVacancyBuilderRoute
  '/interview/$sessionId': typeof InterviewSessionIdRouteWithChildren
  '/interview/setup': typeof InterviewSetupRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/linkedin-review/results': typeof LinkedinReviewResultsRoute
  '/poc/ai-matching': typeof PocAiMatchingRoute
  '/poc/dashboard': typeof PocDashboardRoute
  '/poc/employer-matching': typeof PocEmployerMatchingRoute
  '/poc/recommendations': typeof PocRecommendationsRoute
  '/poc/vacancy-parser': typeof PocVacancyParserRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/candidates/$candidateId': typeof AdminCandidatesCandidateIdRoute
  '/employer/candidate/$candidateId': typeof EmployerCandidateCandidateIdRoute
  '/employer/interview-templates/$templateId': typeof EmployerInterviewTemplatesTemplateIdRouteWithChildren
  '/employer/interview-templates/create': typeof EmployerInterviewTemplatesCreateRoute
  '/employer/interviews/create': typeof EmployerInterviewsCreateRoute
  '/interview/$sessionId/room': typeof InterviewSessionIdRoomRoute
  '/interview/$sessionId/summary': typeof InterviewSessionIdSummaryRoute
  '/employer/interviews/$sessionId/report': typeof EmployerInterviewsSessionIdReportRoute
  '/employer/vacancies/$jobId/candidates': typeof EmployerVacanciesJobIdCandidatesRouteWithChildren
  '/employer/vacancies/$jobId/intelligence': typeof EmployerVacanciesJobIdIntelligenceRoute
  '/employer/vacancies/$jobId/occupation': typeof EmployerVacanciesJobIdOccupationRoute
  '/employer/vacancy/$jobId/optimize': typeof EmployerVacancyJobIdOptimizeRoute
  '/employer/interview-templates/$templateId/report/$invitationId': typeof EmployerInterviewTemplatesTemplateIdReportInvitationIdRoute
  '/employer/vacancies/$jobId/candidates/$candidateId': typeof EmployerVacanciesJobIdCandidatesCandidateIdRoute
  '/employer/vacancies/$jobId/candidates/compare': typeof EmployerVacanciesJobIdCandidatesCompareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/career-pathway': typeof CareerPathwayRoute
  '/caseworker': typeof CaseworkerRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/interview-preparation': typeof InterviewPreparationRoute
  '/jobs': typeof JobsRouteWithChildren
  '/linkedin-review': typeof LinkedinReviewRouteWithChildren
  '/login': typeof LoginRoute
  '/my-cv': typeof MyCvRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/signup': typeof SignupRoute
  '/skills-passport': typeof SkillsPassportRoute
  '/terms': typeof TermsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/candidates': typeof AdminCandidatesRouteWithChildren
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/employers': typeof AdminEmployersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/system-monitoring': typeof AdminSystemMonitoringRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/ops': typeof ApiOpsRoute
  '/api/resume-builder': typeof ApiResumeBuilderRoute
  '/application/$applicationId': typeof ApplicationApplicationIdRoute
  '/caseworker/$candidateId': typeof CaseworkerCandidateIdRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/interview-templates': typeof EmployerInterviewTemplatesRouteWithChildren
  '/employer/interviews': typeof EmployerInterviewsRouteWithChildren
  '/employer/labour-market-intelligence': typeof EmployerLabourMarketIntelligenceRoute
  '/employer/login': typeof EmployerLoginRoute
  '/employer/occupation-intelligence': typeof EmployerOccupationIntelligenceRoute
  '/employer/signup': typeof EmployerSignupRoute
  '/employer/talent-discovery': typeof EmployerTalentDiscoveryRoute
  '/employer/vacancy-builder': typeof EmployerVacancyBuilderRoute
  '/interview/$sessionId': typeof InterviewSessionIdRouteWithChildren
  '/interview/setup': typeof InterviewSetupRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/linkedin-review/results': typeof LinkedinReviewResultsRoute
  '/poc/ai-matching': typeof PocAiMatchingRoute
  '/poc/dashboard': typeof PocDashboardRoute
  '/poc/employer-matching': typeof PocEmployerMatchingRoute
  '/poc/recommendations': typeof PocRecommendationsRoute
  '/poc/vacancy-parser': typeof PocVacancyParserRoute
  '/admin': typeof AdminIndexRoute
  '/admin/candidates/$candidateId': typeof AdminCandidatesCandidateIdRoute
  '/employer/candidate/$candidateId': typeof EmployerCandidateCandidateIdRoute
  '/employer/interview-templates/$templateId': typeof EmployerInterviewTemplatesTemplateIdRouteWithChildren
  '/employer/interview-templates/create': typeof EmployerInterviewTemplatesCreateRoute
  '/employer/interviews/create': typeof EmployerInterviewsCreateRoute
  '/interview/$sessionId/room': typeof InterviewSessionIdRoomRoute
  '/interview/$sessionId/summary': typeof InterviewSessionIdSummaryRoute
  '/employer/interviews/$sessionId/report': typeof EmployerInterviewsSessionIdReportRoute
  '/employer/vacancies/$jobId/candidates': typeof EmployerVacanciesJobIdCandidatesRouteWithChildren
  '/employer/vacancies/$jobId/intelligence': typeof EmployerVacanciesJobIdIntelligenceRoute
  '/employer/vacancies/$jobId/occupation': typeof EmployerVacanciesJobIdOccupationRoute
  '/employer/vacancy/$jobId/optimize': typeof EmployerVacancyJobIdOptimizeRoute
  '/employer/interview-templates/$templateId/report/$invitationId': typeof EmployerInterviewTemplatesTemplateIdReportInvitationIdRoute
  '/employer/vacancies/$jobId/candidates/$candidateId': typeof EmployerVacanciesJobIdCandidatesCandidateIdRoute
  '/employer/vacancies/$jobId/candidates/compare': typeof EmployerVacanciesJobIdCandidatesCompareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/analyze': typeof AnalyzeRoute
  '/career-pathway': typeof CareerPathwayRoute
  '/caseworker': typeof CaseworkerRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/interview-preparation': typeof InterviewPreparationRoute
  '/jobs': typeof JobsRouteWithChildren
  '/linkedin-review': typeof LinkedinReviewRouteWithChildren
  '/login': typeof LoginRoute
  '/my-cv': typeof MyCvRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/signup': typeof SignupRoute
  '/skills-passport': typeof SkillsPassportRoute
  '/terms': typeof TermsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/candidates': typeof AdminCandidatesRouteWithChildren
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/employers': typeof AdminEmployersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/system-monitoring': typeof AdminSystemMonitoringRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/ops': typeof ApiOpsRoute
  '/api/resume-builder': typeof ApiResumeBuilderRoute
  '/application/$applicationId': typeof ApplicationApplicationIdRoute
  '/caseworker/$candidateId': typeof CaseworkerCandidateIdRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/interview-templates': typeof EmployerInterviewTemplatesRouteWithChildren
  '/employer/interviews': typeof EmployerInterviewsRouteWithChildren
  '/employer/labour-market-intelligence': typeof EmployerLabourMarketIntelligenceRoute
  '/employer/login': typeof EmployerLoginRoute
  '/employer/occupation-intelligence': typeof EmployerOccupationIntelligenceRoute
  '/employer/signup': typeof EmployerSignupRoute
  '/employer/talent-discovery': typeof EmployerTalentDiscoveryRoute
  '/employer/vacancy-builder': typeof EmployerVacancyBuilderRoute
  '/interview/$sessionId': typeof InterviewSessionIdRouteWithChildren
  '/interview/setup': typeof InterviewSetupRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/linkedin-review/results': typeof LinkedinReviewResultsRoute
  '/poc/ai-matching': typeof PocAiMatchingRoute
  '/poc/dashboard': typeof PocDashboardRoute
  '/poc/employer-matching': typeof PocEmployerMatchingRoute
  '/poc/recommendations': typeof PocRecommendationsRoute
  '/poc/vacancy-parser': typeof PocVacancyParserRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/candidates/$candidateId': typeof AdminCandidatesCandidateIdRoute
  '/employer/candidate/$candidateId': typeof EmployerCandidateCandidateIdRoute
  '/employer/interview-templates/$templateId': typeof EmployerInterviewTemplatesTemplateIdRouteWithChildren
  '/employer/interview-templates/create': typeof EmployerInterviewTemplatesCreateRoute
  '/employer/interviews/create': typeof EmployerInterviewsCreateRoute
  '/interview/$sessionId/room': typeof InterviewSessionIdRoomRoute
  '/interview/$sessionId/summary': typeof InterviewSessionIdSummaryRoute
  '/employer/interviews/$sessionId/report': typeof EmployerInterviewsSessionIdReportRoute
  '/employer/vacancies/$jobId/candidates': typeof EmployerVacanciesJobIdCandidatesRouteWithChildren
  '/employer/vacancies/$jobId/intelligence': typeof EmployerVacanciesJobIdIntelligenceRoute
  '/employer/vacancies/$jobId/occupation': typeof EmployerVacanciesJobIdOccupationRoute
  '/employer/vacancy/$jobId/optimize': typeof EmployerVacancyJobIdOptimizeRoute
  '/employer/interview-templates/$templateId/report/$invitationId': typeof EmployerInterviewTemplatesTemplateIdReportInvitationIdRoute
  '/employer/vacancies/$jobId/candidates/$candidateId': typeof EmployerVacanciesJobIdCandidatesCandidateIdRoute
  '/employer/vacancies/$jobId/candidates/compare': typeof EmployerVacanciesJobIdCandidatesCompareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/analyze'
    | '/career-pathway'
    | '/caseworker'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/interview-preparation'
    | '/jobs'
    | '/linkedin-review'
    | '/login'
    | '/my-cv'
    | '/privacy'
    | '/results'
    | '/resume-builder'
    | '/signup'
    | '/skills-passport'
    | '/terms'
    | '/admin/audit-logs'
    | '/admin/candidates'
    | '/admin/configuration'
    | '/admin/employers'
    | '/admin/login'
    | '/admin/placements'
    | '/admin/rbac'
    | '/admin/system-monitoring'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/api/interview'
    | '/api/ops'
    | '/api/resume-builder'
    | '/application/$applicationId'
    | '/caseworker/$candidateId'
    | '/employer/dashboard'
    | '/employer/interview-templates'
    | '/employer/interviews'
    | '/employer/labour-market-intelligence'
    | '/employer/login'
    | '/employer/occupation-intelligence'
    | '/employer/signup'
    | '/employer/talent-discovery'
    | '/employer/vacancy-builder'
    | '/interview/$sessionId'
    | '/interview/setup'
    | '/jobs/$jobId'
    | '/linkedin-review/results'
    | '/poc/ai-matching'
    | '/poc/dashboard'
    | '/poc/employer-matching'
    | '/poc/recommendations'
    | '/poc/vacancy-parser'
    | '/admin/'
    | '/admin/candidates/$candidateId'
    | '/employer/candidate/$candidateId'
    | '/employer/interview-templates/$templateId'
    | '/employer/interview-templates/create'
    | '/employer/interviews/create'
    | '/interview/$sessionId/room'
    | '/interview/$sessionId/summary'
    | '/employer/interviews/$sessionId/report'
    | '/employer/vacancies/$jobId/candidates'
    | '/employer/vacancies/$jobId/intelligence'
    | '/employer/vacancies/$jobId/occupation'
    | '/employer/vacancy/$jobId/optimize'
    | '/employer/interview-templates/$templateId/report/$invitationId'
    | '/employer/vacancies/$jobId/candidates/$candidateId'
    | '/employer/vacancies/$jobId/candidates/compare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analyze'
    | '/career-pathway'
    | '/caseworker'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/interview-preparation'
    | '/jobs'
    | '/linkedin-review'
    | '/login'
    | '/my-cv'
    | '/privacy'
    | '/results'
    | '/resume-builder'
    | '/signup'
    | '/skills-passport'
    | '/terms'
    | '/admin/audit-logs'
    | '/admin/candidates'
    | '/admin/configuration'
    | '/admin/employers'
    | '/admin/login'
    | '/admin/placements'
    | '/admin/rbac'
    | '/admin/system-monitoring'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/api/interview'
    | '/api/ops'
    | '/api/resume-builder'
    | '/application/$applicationId'
    | '/caseworker/$candidateId'
    | '/employer/dashboard'
    | '/employer/interview-templates'
    | '/employer/interviews'
    | '/employer/labour-market-intelligence'
    | '/employer/login'
    | '/employer/occupation-intelligence'
    | '/employer/signup'
    | '/employer/talent-discovery'
    | '/employer/vacancy-builder'
    | '/interview/$sessionId'
    | '/interview/setup'
    | '/jobs/$jobId'
    | '/linkedin-review/results'
    | '/poc/ai-matching'
    | '/poc/dashboard'
    | '/poc/employer-matching'
    | '/poc/recommendations'
    | '/poc/vacancy-parser'
    | '/admin'
    | '/admin/candidates/$candidateId'
    | '/employer/candidate/$candidateId'
    | '/employer/interview-templates/$templateId'
    | '/employer/interview-templates/create'
    | '/employer/interviews/create'
    | '/interview/$sessionId/room'
    | '/interview/$sessionId/summary'
    | '/employer/interviews/$sessionId/report'
    | '/employer/vacancies/$jobId/candidates'
    | '/employer/vacancies/$jobId/intelligence'
    | '/employer/vacancies/$jobId/occupation'
    | '/employer/vacancy/$jobId/optimize'
    | '/employer/interview-templates/$templateId/report/$invitationId'
    | '/employer/vacancies/$jobId/candidates/$candidateId'
    | '/employer/vacancies/$jobId/candidates/compare'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/analyze'
    | '/career-pathway'
    | '/caseworker'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/interview-preparation'
    | '/jobs'
    | '/linkedin-review'
    | '/login'
    | '/my-cv'
    | '/privacy'
    | '/results'
    | '/resume-builder'
    | '/signup'
    | '/skills-passport'
    | '/terms'
    | '/admin/audit-logs'
    | '/admin/candidates'
    | '/admin/configuration'
    | '/admin/employers'
    | '/admin/login'
    | '/admin/placements'
    | '/admin/rbac'
    | '/admin/system-monitoring'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/api/interview'
    | '/api/ops'
    | '/api/resume-builder'
    | '/application/$applicationId'
    | '/caseworker/$candidateId'
    | '/employer/dashboard'
    | '/employer/interview-templates'
    | '/employer/interviews'
    | '/employer/labour-market-intelligence'
    | '/employer/login'
    | '/employer/occupation-intelligence'
    | '/employer/signup'
    | '/employer/talent-discovery'
    | '/employer/vacancy-builder'
    | '/interview/$sessionId'
    | '/interview/setup'
    | '/jobs/$jobId'
    | '/linkedin-review/results'
    | '/poc/ai-matching'
    | '/poc/dashboard'
    | '/poc/employer-matching'
    | '/poc/recommendations'
    | '/poc/vacancy-parser'
    | '/admin/'
    | '/admin/candidates/$candidateId'
    | '/employer/candidate/$candidateId'
    | '/employer/interview-templates/$templateId'
    | '/employer/interview-templates/create'
    | '/employer/interviews/create'
    | '/interview/$sessionId/room'
    | '/interview/$sessionId/summary'
    | '/employer/interviews/$sessionId/report'
    | '/employer/vacancies/$jobId/candidates'
    | '/employer/vacancies/$jobId/intelligence'
    | '/employer/vacancies/$jobId/occupation'
    | '/employer/vacancy/$jobId/optimize'
    | '/employer/interview-templates/$templateId/report/$invitationId'
    | '/employer/vacancies/$jobId/candidates/$candidateId'
    | '/employer/vacancies/$jobId/candidates/compare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyzeRoute: typeof AnalyzeRoute
  CareerPathwayRoute: typeof CareerPathwayRoute
  CaseworkerRoute: typeof CaseworkerRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  InterviewPreparationRoute: typeof InterviewPreparationRoute
  JobsRoute: typeof JobsRouteWithChildren
  LinkedinReviewRoute: typeof LinkedinReviewRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyCvRoute: typeof MyCvRoute
  PrivacyRoute: typeof PrivacyRoute
  ResultsRoute: typeof ResultsRoute
  ResumeBuilderRoute: typeof ResumeBuilderRoute
  SignupRoute: typeof SignupRoute
  SkillsPassportRoute: typeof SkillsPassportRoute
  TermsRoute: typeof TermsRoute
  ApiInterviewRoute: typeof ApiInterviewRoute
  ApiOpsRoute: typeof ApiOpsRoute
  ApiResumeBuilderRoute: typeof ApiResumeBuilderRoute
  ApplicationApplicationIdRoute: typeof ApplicationApplicationIdRoute
  EmployerDashboardRoute: typeof EmployerDashboardRoute
  EmployerInterviewTemplatesRoute: typeof EmployerInterviewTemplatesRouteWithChildren
  EmployerInterviewsRoute: typeof EmployerInterviewsRouteWithChildren
  EmployerLabourMarketIntelligenceRoute: typeof EmployerLabourMarketIntelligenceRoute
  EmployerLoginRoute: typeof EmployerLoginRoute
  EmployerOccupationIntelligenceRoute: typeof EmployerOccupationIntelligenceRoute
  EmployerSignupRoute: typeof EmployerSignupRoute
  EmployerTalentDiscoveryRoute: typeof EmployerTalentDiscoveryRoute
  EmployerVacancyBuilderRoute: typeof EmployerVacancyBuilderRoute
  InterviewSessionIdRoute: typeof InterviewSessionIdRouteWithChildren
  InterviewSetupRoute: typeof InterviewSetupRoute
  PocAiMatchingRoute: typeof PocAiMatchingRoute
  PocDashboardRoute: typeof PocDashboardRoute
  PocEmployerMatchingRoute: typeof PocEmployerMatchingRoute
  PocRecommendationsRoute: typeof PocRecommendationsRoute
  PocVacancyParserRoute: typeof PocVacancyParserRoute
  EmployerCandidateCandidateIdRoute: typeof EmployerCandidateCandidateIdRoute
  EmployerVacanciesJobIdCandidatesRoute: typeof EmployerVacanciesJobIdCandidatesRouteWithChildren
  EmployerVacanciesJobIdIntelligenceRoute: typeof EmployerVacanciesJobIdIntelligenceRoute
  EmployerVacanciesJobIdOccupationRoute: typeof EmployerVacanciesJobIdOccupationRoute
  EmployerVacancyJobIdOptimizeRoute: typeof EmployerVacancyJobIdOptimizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills-passport': {
      id: '/skills-passport'
      path: '/skills-passport'
      fullPath: '/skills-passport'
      preLoaderRoute: typeof SkillsPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-builder': {
      id: '/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof ResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-cv': {
      id: '/my-cv'
      path: '/my-cv'
      fullPath: '/my-cv'
      preLoaderRoute: typeof MyCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-review': {
      id: '/linkedin-review'
      path: '/linkedin-review'
      fullPath: '/linkedin-review'
      preLoaderRoute: typeof LinkedinReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-preparation': {
      id: '/interview-preparation'
      path: '/interview-preparation'
      fullPath: '/interview-preparation'
      preLoaderRoute: typeof InterviewPreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caseworker': {
      id: '/caseworker'
      path: '/caseworker'
      fullPath: '/caseworker'
      preLoaderRoute: typeof CaseworkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-pathway': {
      id: '/career-pathway'
      path: '/career-pathway'
      fullPath: '/career-pathway'
      preLoaderRoute: typeof CareerPathwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/poc/vacancy-parser': {
      id: '/poc/vacancy-parser'
      path: '/poc/vacancy-parser'
      fullPath: '/poc/vacancy-parser'
      preLoaderRoute: typeof PocVacancyParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poc/recommendations': {
      id: '/poc/recommendations'
      path: '/poc/recommendations'
      fullPath: '/poc/recommendations'
      preLoaderRoute: typeof PocRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poc/employer-matching': {
      id: '/poc/employer-matching'
      path: '/poc/employer-matching'
      fullPath: '/poc/employer-matching'
      preLoaderRoute: typeof PocEmployerMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poc/dashboard': {
      id: '/poc/dashboard'
      path: '/poc/dashboard'
      fullPath: '/poc/dashboard'
      preLoaderRoute: typeof PocDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poc/ai-matching': {
      id: '/poc/ai-matching'
      path: '/poc/ai-matching'
      fullPath: '/poc/ai-matching'
      preLoaderRoute: typeof PocAiMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-review/results': {
      id: '/linkedin-review/results'
      path: '/results'
      fullPath: '/linkedin-review/results'
      preLoaderRoute: typeof LinkedinReviewResultsRouteImport
      parentRoute: typeof LinkedinReviewRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/interview/setup': {
      id: '/interview/setup'
      path: '/interview/setup'
      fullPath: '/interview/setup'
      preLoaderRoute: typeof InterviewSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$sessionId': {
      id: '/interview/$sessionId'
      path: '/interview/$sessionId'
      fullPath: '/interview/$sessionId'
      preLoaderRoute: typeof InterviewSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/vacancy-builder': {
      id: '/employer/vacancy-builder'
      path: '/employer/vacancy-builder'
      fullPath: '/employer/vacancy-builder'
      preLoaderRoute: typeof EmployerVacancyBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/talent-discovery': {
      id: '/employer/talent-discovery'
      path: '/employer/talent-discovery'
      fullPath: '/employer/talent-discovery'
      preLoaderRoute: typeof EmployerTalentDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/signup': {
      id: '/employer/signup'
      path: '/employer/signup'
      fullPath: '/employer/signup'
      preLoaderRoute: typeof EmployerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/occupation-intelligence': {
      id: '/employer/occupation-intelligence'
      path: '/employer/occupation-intelligence'
      fullPath: '/employer/occupation-intelligence'
      preLoaderRoute: typeof EmployerOccupationIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/login': {
      id: '/employer/login'
      path: '/employer/login'
      fullPath: '/employer/login'
      preLoaderRoute: typeof EmployerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/labour-market-intelligence': {
      id: '/employer/labour-market-intelligence'
      path: '/employer/labour-market-intelligence'
      fullPath: '/employer/labour-market-intelligence'
      preLoaderRoute: typeof EmployerLabourMarketIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/interviews': {
      id: '/employer/interviews'
      path: '/employer/interviews'
      fullPath: '/employer/interviews'
      preLoaderRoute: typeof EmployerInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/interview-templates': {
      id: '/employer/interview-templates'
      path: '/employer/interview-templates'
      fullPath: '/employer/interview-templates'
      preLoaderRoute: typeof EmployerInterviewTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/dashboard': {
      id: '/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof EmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caseworker/$candidateId': {
      id: '/caseworker/$candidateId'
      path: '/$candidateId'
      fullPath: '/caseworker/$candidateId'
      preLoaderRoute: typeof CaseworkerCandidateIdRouteImport
      parentRoute: typeof CaseworkerRoute
    }
    '/application/$applicationId': {
      id: '/application/$applicationId'
      path: '/application/$applicationId'
      fullPath: '/application/$applicationId'
      preLoaderRoute: typeof ApplicationApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume-builder': {
      id: '/api/resume-builder'
      path: '/api/resume-builder'
      fullPath: '/api/resume-builder'
      preLoaderRoute: typeof ApiResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops': {
      id: '/api/ops'
      path: '/api/ops'
      fullPath: '/api/ops'
      preLoaderRoute: typeof ApiOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview': {
      id: '/api/interview'
      path: '/api/interview'
      fullPath: '/api/interview'
      preLoaderRoute: typeof ApiInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/taxonomy': {
      id: '/admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AdminTaxonomyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-monitoring': {
      id: '/admin/system-monitoring'
      path: '/system-monitoring'
      fullPath: '/admin/system-monitoring'
      preLoaderRoute: typeof AdminSystemMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rbac': {
      id: '/admin/rbac'
      path: '/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof AdminRbacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/placements': {
      id: '/admin/placements'
      path: '/placements'
      fullPath: '/admin/placements'
      preLoaderRoute: typeof AdminPlacementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employers': {
      id: '/admin/employers'
      path: '/employers'
      fullPath: '/admin/employers'
      preLoaderRoute: typeof AdminEmployersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuration': {
      id: '/admin/configuration'
      path: '/configuration'
      fullPath: '/admin/configuration'
      preLoaderRoute: typeof AdminConfigurationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/interview/$sessionId/summary': {
      id: '/interview/$sessionId/summary'
      path: '/summary'
      fullPath: '/interview/$sessionId/summary'
      preLoaderRoute: typeof InterviewSessionIdSummaryRouteImport
      parentRoute: typeof InterviewSessionIdRoute
    }
    '/interview/$sessionId/room': {
      id: '/interview/$sessionId/room'
      path: '/room'
      fullPath: '/interview/$sessionId/room'
      preLoaderRoute: typeof InterviewSessionIdRoomRouteImport
      parentRoute: typeof InterviewSessionIdRoute
    }
    '/employer/interviews/create': {
      id: '/employer/interviews/create'
      path: '/create'
      fullPath: '/employer/interviews/create'
      preLoaderRoute: typeof EmployerInterviewsCreateRouteImport
      parentRoute: typeof EmployerInterviewsRoute
    }
    '/employer/interview-templates/create': {
      id: '/employer/interview-templates/create'
      path: '/create'
      fullPath: '/employer/interview-templates/create'
      preLoaderRoute: typeof EmployerInterviewTemplatesCreateRouteImport
      parentRoute: typeof EmployerInterviewTemplatesRoute
    }
    '/employer/interview-templates/$templateId': {
      id: '/employer/interview-templates/$templateId'
      path: '/$templateId'
      fullPath: '/employer/interview-templates/$templateId'
      preLoaderRoute: typeof EmployerInterviewTemplatesTemplateIdRouteImport
      parentRoute: typeof EmployerInterviewTemplatesRoute
    }
    '/employer/candidate/$candidateId': {
      id: '/employer/candidate/$candidateId'
      path: '/employer/candidate/$candidateId'
      fullPath: '/employer/candidate/$candidateId'
      preLoaderRoute: typeof EmployerCandidateCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates/$candidateId': {
      id: '/admin/candidates/$candidateId'
      path: '/$candidateId'
      fullPath: '/admin/candidates/$candidateId'
      preLoaderRoute: typeof AdminCandidatesCandidateIdRouteImport
      parentRoute: typeof AdminCandidatesRoute
    }
    '/employer/vacancy/$jobId/optimize': {
      id: '/employer/vacancy/$jobId/optimize'
      path: '/employer/vacancy/$jobId/optimize'
      fullPath: '/employer/vacancy/$jobId/optimize'
      preLoaderRoute: typeof EmployerVacancyJobIdOptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/vacancies/$jobId/occupation': {
      id: '/employer/vacancies/$jobId/occupation'
      path: '/employer/vacancies/$jobId/occupation'
      fullPath: '/employer/vacancies/$jobId/occupation'
      preLoaderRoute: typeof EmployerVacanciesJobIdOccupationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/vacancies/$jobId/intelligence': {
      id: '/employer/vacancies/$jobId/intelligence'
      path: '/employer/vacancies/$jobId/intelligence'
      fullPath: '/employer/vacancies/$jobId/intelligence'
      preLoaderRoute: typeof EmployerVacanciesJobIdIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/vacancies/$jobId/candidates': {
      id: '/employer/vacancies/$jobId/candidates'
      path: '/employer/vacancies/$jobId/candidates'
      fullPath: '/employer/vacancies/$jobId/candidates'
      preLoaderRoute: typeof EmployerVacanciesJobIdCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/interviews/$sessionId/report': {
      id: '/employer/interviews/$sessionId/report'
      path: '/$sessionId/report'
      fullPath: '/employer/interviews/$sessionId/report'
      preLoaderRoute: typeof EmployerInterviewsSessionIdReportRouteImport
      parentRoute: typeof EmployerInterviewsRoute
    }
    '/employer/vacancies/$jobId/candidates/compare': {
      id: '/employer/vacancies/$jobId/candidates/compare'
      path: '/compare'
      fullPath: '/employer/vacancies/$jobId/candidates/compare'
      preLoaderRoute: typeof EmployerVacanciesJobIdCandidatesCompareRouteImport
      parentRoute: typeof EmployerVacanciesJobIdCandidatesRoute
    }
    '/employer/vacancies/$jobId/candidates/$candidateId': {
      id: '/employer/vacancies/$jobId/candidates/$candidateId'
      path: '/$candidateId'
      fullPath: '/employer/vacancies/$jobId/candidates/$candidateId'
      preLoaderRoute: typeof EmployerVacanciesJobIdCandidatesCandidateIdRouteImport
      parentRoute: typeof EmployerVacanciesJobIdCandidatesRoute
    }
    '/employer/interview-templates/$templateId/report/$invitationId': {
      id: '/employer/interview-templates/$templateId/report/$invitationId'
      path: '/report/$invitationId'
      fullPath: '/employer/interview-templates/$templateId/report/$invitationId'
      preLoaderRoute: typeof EmployerInterviewTemplatesTemplateIdReportInvitationIdRouteImport
      parentRoute: typeof EmployerInterviewTemplatesTemplateIdRoute
    }
  }
}

interface AdminCandidatesRouteChildren {
  AdminCandidatesCandidateIdRoute: typeof AdminCandidatesCandidateIdRoute
}

const AdminCandidatesRouteChildren: AdminCandidatesRouteChildren = {
  AdminCandidatesCandidateIdRoute: AdminCandidatesCandidateIdRoute,
}

const AdminCandidatesRouteWithChildren = AdminCandidatesRoute._addFileChildren(
  AdminCandidatesRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCandidatesRoute: typeof AdminCandidatesRouteWithChildren
  AdminConfigurationRoute: typeof AdminConfigurationRoute
  AdminEmployersRoute: typeof AdminEmployersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPlacementsRoute: typeof AdminPlacementsRoute
  AdminRbacRoute: typeof AdminRbacRoute
  AdminSystemMonitoringRoute: typeof AdminSystemMonitoringRoute
  AdminTaxonomyRoute: typeof AdminTaxonomyRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCandidatesRoute: AdminCandidatesRouteWithChildren,
  AdminConfigurationRoute: AdminConfigurationRoute,
  AdminEmployersRoute: AdminEmployersRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPlacementsRoute: AdminPlacementsRoute,
  AdminRbacRoute: AdminRbacRoute,
  AdminSystemMonitoringRoute: AdminSystemMonitoringRoute,
  AdminTaxonomyRoute: AdminTaxonomyRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CaseworkerRouteChildren {
  CaseworkerCandidateIdRoute: typeof CaseworkerCandidateIdRoute
}

const CaseworkerRouteChildren: CaseworkerRouteChildren = {
  CaseworkerCandidateIdRoute: CaseworkerCandidateIdRoute,
}

const CaseworkerRouteWithChildren = CaseworkerRoute._addFileChildren(
  CaseworkerRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface LinkedinReviewRouteChildren {
  LinkedinReviewResultsRoute: typeof LinkedinReviewResultsRoute
}

const LinkedinReviewRouteChildren: LinkedinReviewRouteChildren = {
  LinkedinReviewResultsRoute: LinkedinReviewResultsRoute,
}

const LinkedinReviewRouteWithChildren = LinkedinReviewRoute._addFileChildren(
  LinkedinReviewRouteChildren,
)

interface EmployerInterviewTemplatesTemplateIdRouteChildren {
  EmployerInterviewTemplatesTemplateIdReportInvitationIdRoute: typeof EmployerInterviewTemplatesTemplateIdReportInvitationIdRoute
}

const EmployerInterviewTemplatesTemplateIdRouteChildren: EmployerInterviewTemplatesTemplateIdRouteChildren =
  {
    EmployerInterviewTemplatesTemplateIdReportInvitationIdRoute:
      EmployerInterviewTemplatesTemplateIdReportInvitationIdRoute,
  }

const EmployerInterviewTemplatesTemplateIdRouteWithChildren =
  EmployerInterviewTemplatesTemplateIdRoute._addFileChildren(
    EmployerInterviewTemplatesTemplateIdRouteChildren,
  )

interface EmployerInterviewTemplatesRouteChildren {
  EmployerInterviewTemplatesTemplateIdRoute: typeof EmployerInterviewTemplatesTemplateIdRouteWithChildren
  EmployerInterviewTemplatesCreateRoute: typeof EmployerInterviewTemplatesCreateRoute
}

const EmployerInterviewTemplatesRouteChildren: EmployerInterviewTemplatesRouteChildren =
  {
    EmployerInterviewTemplatesTemplateIdRoute:
      EmployerInterviewTemplatesTemplateIdRouteWithChildren,
    EmployerInterviewTemplatesCreateRoute:
      EmployerInterviewTemplatesCreateRoute,
  }

const EmployerInterviewTemplatesRouteWithChildren =
  EmployerInterviewTemplatesRoute._addFileChildren(
    EmployerInterviewTemplatesRouteChildren,
  )

interface EmployerInterviewsRouteChildren {
  EmployerInterviewsCreateRoute: typeof EmployerInterviewsCreateRoute
  EmployerInterviewsSessionIdReportRoute: typeof EmployerInterviewsSessionIdReportRoute
}

const EmployerInterviewsRouteChildren: EmployerInterviewsRouteChildren = {
  EmployerInterviewsCreateRoute: EmployerInterviewsCreateRoute,
  EmployerInterviewsSessionIdReportRoute:
    EmployerInterviewsSessionIdReportRoute,
}

const EmployerInterviewsRouteWithChildren =
  EmployerInterviewsRoute._addFileChildren(EmployerInterviewsRouteChildren)

interface InterviewSessionIdRouteChildren {
  InterviewSessionIdRoomRoute: typeof InterviewSessionIdRoomRoute
  InterviewSessionIdSummaryRoute: typeof InterviewSessionIdSummaryRoute
}

const InterviewSessionIdRouteChildren: InterviewSessionIdRouteChildren = {
  InterviewSessionIdRoomRoute: InterviewSessionIdRoomRoute,
  InterviewSessionIdSummaryRoute: InterviewSessionIdSummaryRoute,
}

const InterviewSessionIdRouteWithChildren =
  InterviewSessionIdRoute._addFileChildren(InterviewSessionIdRouteChildren)

interface EmployerVacanciesJobIdCandidatesRouteChildren {
  EmployerVacanciesJobIdCandidatesCandidateIdRoute: typeof EmployerVacanciesJobIdCandidatesCandidateIdRoute
  EmployerVacanciesJobIdCandidatesCompareRoute: typeof EmployerVacanciesJobIdCandidatesCompareRoute
}

const EmployerVacanciesJobIdCandidatesRouteChildren: EmployerVacanciesJobIdCandidatesRouteChildren =
  {
    EmployerVacanciesJobIdCandidatesCandidateIdRoute:
      EmployerVacanciesJobIdCandidatesCandidateIdRoute,
    EmployerVacanciesJobIdCandidatesCompareRoute:
      EmployerVacanciesJobIdCandidatesCompareRoute,
  }

const EmployerVacanciesJobIdCandidatesRouteWithChildren =
  EmployerVacanciesJobIdCandidatesRoute._addFileChildren(
    EmployerVacanciesJobIdCandidatesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyzeRoute: AnalyzeRoute,
  CareerPathwayRoute: CareerPathwayRoute,
  CaseworkerRoute: CaseworkerRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  InterviewPreparationRoute: InterviewPreparationRoute,
  JobsRoute: JobsRouteWithChildren,
  LinkedinReviewRoute: LinkedinReviewRouteWithChildren,
  LoginRoute: LoginRoute,
  MyCvRoute: MyCvRoute,
  PrivacyRoute: PrivacyRoute,
  ResultsRoute: ResultsRoute,
  ResumeBuilderRoute: ResumeBuilderRoute,
  SignupRoute: SignupRoute,
  SkillsPassportRoute: SkillsPassportRoute,
  TermsRoute: TermsRoute,
  ApiInterviewRoute: ApiInterviewRoute,
  ApiOpsRoute: ApiOpsRoute,
  ApiResumeBuilderRoute: ApiResumeBuilderRoute,
  ApplicationApplicationIdRoute: ApplicationApplicationIdRoute,
  EmployerDashboardRoute: EmployerDashboardRoute,
  EmployerInterviewTemplatesRoute: EmployerInterviewTemplatesRouteWithChildren,
  EmployerInterviewsRoute: EmployerInterviewsRouteWithChildren,
  EmployerLabourMarketIntelligenceRoute: EmployerLabourMarketIntelligenceRoute,
  EmployerLoginRoute: EmployerLoginRoute,
  EmployerOccupationIntelligenceRoute: EmployerOccupationIntelligenceRoute,
  EmployerSignupRoute: EmployerSignupRoute,
  EmployerTalentDiscoveryRoute: EmployerTalentDiscoveryRoute,
  EmployerVacancyBuilderRoute: EmployerVacancyBuilderRoute,
  InterviewSessionIdRoute: InterviewSessionIdRouteWithChildren,
  InterviewSetupRoute: InterviewSetupRoute,
  PocAiMatchingRoute: PocAiMatchingRoute,
  PocDashboardRoute: PocDashboardRoute,
  PocEmployerMatchingRoute: PocEmployerMatchingRoute,
  PocRecommendationsRoute: PocRecommendationsRoute,
  PocVacancyParserRoute: PocVacancyParserRoute,
  EmployerCandidateCandidateIdRoute: EmployerCandidateCandidateIdRoute,
  EmployerVacanciesJobIdCandidatesRoute:
    EmployerVacanciesJobIdCandidatesRouteWithChildren,
  EmployerVacanciesJobIdIntelligenceRoute:
    EmployerVacanciesJobIdIntelligenceRoute,
  EmployerVacanciesJobIdOccupationRoute: EmployerVacanciesJobIdOccupationRoute,
  EmployerVacancyJobIdOptimizeRoute: EmployerVacancyJobIdOptimizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
